module.exports = [
  {
    "product_id": 650371,
    "user_id": 85791,
    "category_id": 19,
    "product_name": "Hindustan Ambassador",
    "product_description": "Draw hope among information.",
    "value": 3233,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-06-25"
  },
  {
    "product_id": 650372,
    "user_id": 45449,
    "category_id": 16,
    "product_name": "Renault Symbol",
    "product_description": "Herself its push son enter.",
    "value": 5372,
    "up_for_trade": "False",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-04-10"
  },
  {
    "product_id": 650373,
    "user_id": 55768,
    "category_id": 3,
    "product_name": "SEAT Ibiza",
    "product_description": "Institution avoid wish nature take everyone.",
    "value": 4489,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-02-20"
  },
  {
    "product_id": 650374,
    "user_id": 91173,
    "category_id": 5,
    "product_name": "Pontiac Grand Am",
    "product_description": "Compare choose month much.",
    "value": 7591,
    "up_for_trade": "False",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-10-10",
    "posted_date": "2017-07-14"
  },
  {
    "product_id": 650375,
    "user_id": 22136,
    "category_id": 4,
    "product_name": "Eagle Talon",
    "product_description": "Six audience conference know involve.",
    "value": 4707,
    "up_for_trade": "True",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-11-26"
  },
  {
    "product_id": 650376,
    "user_id": 54079,
    "category_id": 16,
    "product_name": "Zaporozhets",
    "product_description": "Process career its although almost.",
    "value": 2719,
    "up_for_trade": "True",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-10-07",
    "posted_date": "2017-04-30"
  },
  {
    "product_id": 650377,
    "user_id": 93140,
    "category_id": 0,
    "product_name": "Tesla Model S",
    "product_description": "Yet final who hospital woman expect.",
    "value": 8401,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-06-04",
    "posted_date": "2017-01-06"
  },
  {
    "product_id": 650378,
    "user_id": 88797,
    "category_id": 6,
    "product_name": "Aston Martin DB7",
    "product_description": "Ball right special record without all total.",
    "value": 6556,
    "up_for_trade": "False",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-04-22",
    "posted_date": "2017-04-01"
  },
  {
    "product_id": 650379,
    "user_id": 99193,
    "category_id": 2,
    "product_name": "SEAT Ibiza",
    "product_description": "Answer coach now really case far simple sit.",
    "value": 9078,
    "up_for_trade": "True",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-03-30"
  },
  {
    "product_id": 650380,
    "user_id": 8813,
    "category_id": 0,
    "product_name": "Volkswagen Beetle",
    "product_description": "North foot agreement open.",
    "value": 9528,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-06-30",
    "posted_date": "2017-05-08"
  },
  {
    "product_id": 650381,
    "user_id": 28081,
    "category_id": 16,
    "product_name": "Buick LeSabre",
    "product_description": "Popular language live.",
    "value": 8121,
    "up_for_trade": "False",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-01-03"
  },
  {
    "product_id": 650382,
    "user_id": 60653,
    "category_id": 13,
    "product_name": "Lotus Elise",
    "product_description": "Task city case in will current we.",
    "value": 9995,
    "up_for_trade": "True",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-06-10",
    "posted_date": "2017-09-23"
  },
  {
    "product_id": 650383,
    "user_id": 94376,
    "category_id": 15,
    "product_name": "Imperial Crown",
    "product_description": "Certain price view account project entire year media.",
    "value": 1097,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-07-21",
    "posted_date": "2017-10-17"
  },
  {
    "product_id": 650384,
    "user_id": 55888,
    "category_id": 15,
    "product_name": "Mazda Familia",
    "product_description": "Wonder ground get American there born.",
    "value": 4739,
    "up_for_trade": "True",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-09-21",
    "posted_date": "2017-03-13"
  },
  {
    "product_id": 650385,
    "user_id": 55924,
    "category_id": 9,
    "product_name": "De Tomaso Pantera",
    "product_description": "Including such strong pass newspaper fact.",
    "value": 4784,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-10-08",
    "posted_date": "2017-02-24"
  },
  {
    "product_id": 650386,
    "user_id": 10120,
    "category_id": 0,
    "product_name": "Rolls-Royce Silver Shadow",
    "product_description": "War listen lot health when member business.",
    "value": 761,
    "up_for_trade": "False",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-11-22",
    "posted_date": "2017-03-29"
  },
  {
    "product_id": 650387,
    "user_id": 43883,
    "category_id": 0,
    "product_name": "Zaporozhets",
    "product_description": "Serious cover among nor at despite maybe.",
    "value": 6355,
    "up_for_trade": "False",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-12-20"
  },
  {
    "product_id": 650388,
    "user_id": 50968,
    "category_id": 18,
    "product_name": "Hindustan Ambassador",
    "product_description": "Mr report contain me individual agreement style.",
    "value": 8296,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-04-26"
  },
  {
    "product_id": 650389,
    "user_id": 33764,
    "category_id": 6,
    "product_name": "Excalibur Series II",
    "product_description": "Radio ago probably turn sit general candidate admit.",
    "value": 8250,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-08-20",
    "posted_date": "2017-06-12"
  },
  {
    "product_id": 650390,
    "user_id": 56132,
    "category_id": 10,
    "product_name": "Imperial Crown",
    "product_description": "Level experience car system account charge.",
    "value": 2808,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-02-22"
  },
  {
    "product_id": 650391,
    "user_id": 40084,
    "category_id": 4,
    "product_name": "De Tomaso Pantera",
    "product_description": "Require realize want science director sea.",
    "value": 3902,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-11-23"
  },
  {
    "product_id": 650392,
    "user_id": 98962,
    "category_id": 7,
    "product_name": "Plymouth Fury",
    "product_description": "Mean on indicate.",
    "value": 673,
    "up_for_trade": "False",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-11-25",
    "posted_date": "2017-11-22"
  },
  {
    "product_id": 650393,
    "user_id": 8939,
    "category_id": 0,
    "product_name": "Chevrolet Volt",
    "product_description": "Affect against happy turn sound oil.",
    "value": 8747,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-11-28"
  },
  {
    "product_id": 650394,
    "user_id": 6981,
    "category_id": 6,
    "product_name": "Smart Fortwo",
    "product_description": "Whom art myself buy.",
    "value": 2796,
    "up_for_trade": "False",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-12-02",
    "posted_date": "2017-01-18"
  },
  {
    "product_id": 650395,
    "user_id": 28883,
    "category_id": 0,
    "product_name": "Mazda MX-5",
    "product_description": "Ball rise serious generation society serious.",
    "value": 5129,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-04-09",
    "posted_date": "2017-08-29"
  },
  {
    "product_id": 650396,
    "user_id": 14760,
    "category_id": 7,
    "product_name": "Toyota Corolla",
    "product_description": "Activity past between my finally.",
    "value": 3206,
    "up_for_trade": "False",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-08-26",
    "posted_date": "2017-07-17"
  },
  {
    "product_id": 650397,
    "user_id": 371,
    "category_id": 4,
    "product_name": "Toyota Corolla",
    "product_description": "Weight view rate front model.",
    "value": 9208,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-05-17"
  },
  {
    "product_id": 650398,
    "user_id": 39118,
    "category_id": 13,
    "product_name": "Lamborghini Gallardo",
    "product_description": "High nice base.",
    "value": 7246,
    "up_for_trade": "True",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-05-03"
  },
  {
    "product_id": 650399,
    "user_id": 40716,
    "category_id": 3,
    "product_name": "Chrysler Newport",
    "product_description": "Probably well sound.",
    "value": 9543,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-11-16"
  },
  {
    "product_id": 650400,
    "user_id": 80263,
    "category_id": 10,
    "product_name": "Packard Eight",
    "product_description": "Establish great husband.",
    "value": 9025,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-09-18",
    "posted_date": "2017-07-25"
  },
  {
    "product_id": 650401,
    "user_id": 1785,
    "category_id": 2,
    "product_name": "Renault Symbol",
    "product_description": "Number more drive despite would artist position.",
    "value": 6558,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-11-10"
  },
  {
    "product_id": 650402,
    "user_id": 71885,
    "category_id": 16,
    "product_name": "Ford Falcon",
    "product_description": "Music site enough their can describe.",
    "value": 3979,
    "up_for_trade": "False",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-07-02",
    "posted_date": "2017-06-07"
  },
  {
    "product_id": 650403,
    "user_id": 87362,
    "category_id": 14,
    "product_name": "Metropolitan",
    "product_description": "Sing defense let author foreign pressure.",
    "value": 6629,
    "up_for_trade": "False",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-06-28",
    "posted_date": "2017-08-14"
  },
  {
    "product_id": 650404,
    "user_id": 51990,
    "category_id": 17,
    "product_name": "Porsche 911",
    "product_description": "Material his place investment.",
    "value": 4898,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-03-13"
  },
  {
    "product_id": 650405,
    "user_id": 8002,
    "category_id": 1,
    "product_name": "Toyota Prius",
    "product_description": "Race cold clearly film industry western.",
    "value": 3775,
    "up_for_trade": "False",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-07-13",
    "posted_date": "2017-11-05"
  },
  {
    "product_id": 650406,
    "user_id": 58583,
    "category_id": 18,
    "product_name": "SEAT Ibiza",
    "product_description": "Say true quality technology put data support.",
    "value": 7134,
    "up_for_trade": "True",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-01-05",
    "posted_date": "2017-04-30"
  },
  {
    "product_id": 650407,
    "user_id": 99403,
    "category_id": 9,
    "product_name": "Chrysler Newport",
    "product_description": "Imagine cut hundred candidate instead far ten.",
    "value": 8901,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-09-17"
  },
  {
    "product_id": 650408,
    "user_id": 43442,
    "category_id": 18,
    "product_name": "Series/Defender",
    "product_description": "Imagine catch interesting nor go.",
    "value": 4458,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-12-24"
  },
  {
    "product_id": 650409,
    "user_id": 48897,
    "category_id": 18,
    "product_name": "Plymouth Fury",
    "product_description": "Suffer its chair draw brother without.",
    "value": 1781,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-06-11"
  },
  {
    "product_id": 650410,
    "user_id": 58240,
    "category_id": 9,
    "product_name": "Cadillac De Ville",
    "product_description": "Management data deal technology onto own until.",
    "value": 2596,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-09-19",
    "posted_date": "2017-04-27"
  },
  {
    "product_id": 650411,
    "user_id": 94548,
    "category_id": 3,
    "product_name": "Fiat Uno",
    "product_description": "Nice within box others language a happy central.",
    "value": 2958,
    "up_for_trade": "True",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-05-07"
  },
  {
    "product_id": 650412,
    "user_id": 62877,
    "category_id": 11,
    "product_name": "Mercury Grand Marquis",
    "product_description": "Understand window mind paper forget feeling.",
    "value": 7219,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-10-18"
  },
  {
    "product_id": 650413,
    "user_id": 91475,
    "category_id": 8,
    "product_name": "AMC Hornet",
    "product_description": "Security instead enough wind lawyer five.",
    "value": 4534,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-09-30"
  },
  {
    "product_id": 650414,
    "user_id": 85521,
    "category_id": 1,
    "product_name": "Checker Marathon",
    "product_description": "Form wish green.",
    "value": 4134,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-04-28"
  },
  {
    "product_id": 650415,
    "user_id": 68729,
    "category_id": 4,
    "product_name": "Renault Clio",
    "product_description": "Police green answer throughout.",
    "value": 2633,
    "up_for_trade": "False",
    "public": "False",
    "sold": "True",
    "sold_date": "2018-09-03",
    "posted_date": "2017-08-27"
  },
  {
    "product_id": 650416,
    "user_id": 1694,
    "category_id": 5,
    "product_name": "Edsel Ranger",
    "product_description": "Evidence them tough between.",
    "value": 2140,
    "up_for_trade": "True",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-11-11"
  },
  {
    "product_id": 650417,
    "user_id": 67634,
    "category_id": 3,
    "product_name": "Toyota Corolla",
    "product_description": "Candidate wait region suffer various mean seat field.",
    "value": 2668,
    "up_for_trade": "False",
    "public": "True",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-09-30"
  },
  {
    "product_id": 650418,
    "user_id": 35164,
    "category_id": 5,
    "product_name": "Mazda Familia",
    "product_description": "Perhaps tend trial simply eat.",
    "value": 3163,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-07-16",
    "posted_date": "2017-06-09"
  },
  {
    "product_id": 650419,
    "user_id": 16216,
    "category_id": 3,
    "product_name": "Packard Eight",
    "product_description": "Student ground analysis understand need.",
    "value": 5885,
    "up_for_trade": "True",
    "public": "True",
    "sold": "True",
    "sold_date": "2018-09-24",
    "posted_date": "2017-08-02"
  },
  {
    "product_id": 650420,
    "user_id": 75169,
    "category_id": 11,
    "product_name": "Jaguar XJ",
    "product_description": "Baby large measure.",
    "value": 5007,
    "up_for_trade": "False",
    "public": "False",
    "sold": "False",
    "sold_date": null,
    "posted_date": "2017-01-16"
  }
];
